spring:
  application:
    name: authorization-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Registration
          uri: lb://user-service
          predicates:
            - Path=/registration
          filters:
            - RewritePath=/registration, /v1/users
        - id: Authentication
          uri: lb://user-service
          predicates:
            - Path=/authentication
          filters:
            - AuthenticationFilter
            - RewritePath=/authentication, /v1/users/authentication
        - id: Authorization
          uri: lb://user-service
          predicates:
            - Path=/authentication
          filters:
            - AuthorizationFilter